export const BANK_OPTIONS = [
  "AB Bank",
  "Agrani Bank",
  "Al-Arafah Islami Bank",
  "Bank Asia",
  "BRAC Bank",
  "City Bank",
  "Dutch-Bangla Bank",
  "Eastern Bank",
  "EXIM Bank",
  "IFIC Bank",
  "Islami Bank Bangladesh",
  "Jamuna Bank",
  "Janata Bank",
  "Mercantile Bank",
  "Midland Bank",
  "Mutual Trust Bank",
  "National Bank",
  "NCC Bank",
  "One Bank",
  "Prime Bank",
  "Pubali Bank",
  "Rupali Bank",
  "Shahjalal Islami Bank",
  "Social Islami Bank",
  "Sonali Bank",
  "Southeast Bank",
  "Standard Bank",
  "Standard Chartered Bank",
  "Trust Bank",
  "United Commercial Bank",
  "Uttara Bank",
];
